name: QMK Firmware Build # Nome que aparece no GitHub Actions

on:
  push:
    branches:
      - main # Quando houver mudanças enviadas para a branch 'main'
  workflow_dispatch: # Permite que você clique num botão no GitHub para rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest # Usa um computador virtual Linux para rodar o trabalho

    container:
      image: qmkfirmware/qmk_cli:latest # Usa a ferramenta QMK oficial. Ela já tem tudo pronto!

    steps:
    - name: Baixar meu código (repositório)
      uses: actions/checkout@v4

    - name: Configurar ambiente QMK
      run: |
        qmk setup -y

    - name: Encontrar o caminho do QMK Firmware
      id: qmk_path
      run: |
        echo "QMK_PATH=$(qmk config user.qmk_firmware)" >> $GITHUB_OUTPUT

    - name: Copiar meu keymap para o QMK Firmware
      run: |
        # Este passo copia a pasta 'keyboards' do SEU repositório (que contem o seu keymap)
        # para a pasta 'keyboards' do QMK Firmware dentro do ambiente de compilação.
        cp -r ${{ github.workspace }}/keyboards ${{ steps.qmk_path.outputs.QMK_PATH }}/keyboards

    - name: Compilar o Firmware
      run: |
        # MUITO IMPORTANTE: SUBSTITUA 'seu_teclado' e 'seu_keymap' pelos nomes corretos do SEU teclado e SEU keymap!
        # Exemplo: qmk compile -kb dz60rgb -km lucas
        qmk compile -kb seu_teclado -km seu_keymap
      working-directory: ${{ steps.qmk_path.outputs.QMK_PATH }} # Garante que o comando compile rode no lugar certo

    - name: Salvar o Firmware Compilado (artefato)
      uses: actions/upload-artifact@v4
      with:
        name: meu_firmware_qmk # Nome do arquivo que você vai baixar
        # Adapte a extensão (.hex, .bin, .uf2) de acordo com o que seu teclado usa.
        path: ${{ steps.qmk_path.outputs.QMK_PATH }}/*.hex
        # Se você não sabe a extensão exata, pode tentar todas comuns:
        # path: ${{ steps.qmk_path.outputs.QMK_PATH }}/*.{hex,bin,uf2}
